### ISSUE TITLE
Implement unic-ucd-block

### ISSUE THREAD

**Issue by behnam** [open-i18n/rust-unic#206]
Provides access to char property:
* `Block` (Enumerated)

Also let's have two iterators:
* All assigned/defined Unicode Blocks
* A character iterator that only walks on character ranges inside these blocks. This is very helpful for reducing the range of chars we test in integration tests, which is wasting a lot of CPU also walking on the ~75% of the code space that's not assigned.

References:
* http://www.unicode.org/reports/tr44/tr44-4.html#Script
* http://www.unicode.org/Public/UCD/latest/ucd/Blocks.txt

Consistency tests:
* Any character assigned should have a block.
* Some blocks contain unassigned characters.

Cross-component tests:
* IIRC, each Block can contain characters from one non-Common/Unknown Script. (GH-137)

Similar crates:
N/A

**Comment by eyeplum** [comment]
While #217 is waiting for code review, I will try to implement this one.

**Comment by behnam** [comment]
Thanks, @eyeplum! I already have a half-baked implementation on my laptop. If you haven't started yet, maybe wait a few days before you start?

**Comment by eyeplum** [comment]
@behnam Sure!

**Comment by behnam** [comment]
Thanks, @eyeplum, for wrapping this up! 😄
