### ISSUE TITLE
Test Unicode 11.0 Beta files

### ISSUE THREAD

**Issue by behnam** [open-i18n/rust-unic#219]
We want to test new Unicode 11.0 data to make sure:
- UNIC is compatible with new data.
- There are no errors in the source data.

Source data files:
- https://www.unicode.org/Public/11.0.0/

See Also:
- http://blog.unicode.org/2018/03/unicode-110-beta-review.html
- http://unicode.org/versions/Unicode11.0.0/

**Comment by CAD97** [comment]
Assuming everything goes perfectly, it should be as simple as changing one line... 

https://github.com/behnam/rust-unic/blob/a2d51096c5e3f8faf727f87e716ed6db5daf04bc/data/sources.toml#L1-L3

and then rerunning the download script `cargo run --package=unic-data`.

**Comment by behnam** [comment]
Automated way wouldn't work that well, because the beta directories, although named similar to the normal release (:facepalm:), do not include all the files, but only those changed so far. So... needs manual work.

As a side note, @CAD97, the hyper client doesn't check HTTP Response status code and saves 404 HTML content into destinations. Would be good to just report and skip the file in those cases. What do you think? Filing another task for it?

**Comment by CAD97** [comment]
Maybe I should have checked the directory before assuming 🙃 but it should be possible without touching the code just by modifying sources.toml to refer to and rename the files in question.

I filed #220 for handling bad responses.

**Comment by Alexendoo** [comment]
Since unicode 11 was released, the directories now contain the final data

**Comment by behnam** [comment]
Tracking Unicode 11.0-related updates in #259. No need to keep this open anymore.
