### ISSUE TITLE
ucd/ident: Add test for Pattern Syntax/Whitespace data

### ISSUE THREAD

**Issue by declanvk** [open-i18n/rust-unic#254]
Hello,

I noticed that the pattern whitespace property is incorrectly using the `pattern_syntax.rsv` table.

https://github.com/open-i18n/rust-unic/blob/6c6702a0a16185a3b075cfce37b6d34342198765/unic/ucd/ident/src/lib.rs#L125-L131

I've opened a PR with the simple substitution, #253

Thanks,
Declan

**Comment by behnam** [comment]
Thanks, @declanvk, for filing the issue!

Unfortunately we haven't had unit tests for these tables, hence not catching the problem earlier. Fix is being landed in https://github.com/open-i18n/rust-unic/pull/255, but let's keep this open to also add some basic unit tests!

**Comment by behnam** [comment]
I'm going to make a release, `v0.9.0`, soon, to deploy the fix for this.
